default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("PGHOST") { "localhost" } %>
  username: <%= ENV.fetch("PGUSER") { "postgres" } %>
  password: <%= ENV.fetch("PGPASSWORD") { "" } %>

development:
  <<: *default
  database: dr_consults_app_development

test:
  <<: *default
  database: dr_consults_app_test




production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>